<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>lasso</string>
		<string>las</string>
		<string>inc</string>
	</array>
	<key>firstLineMatch</key>
	<string>&lt;\?(?i:=|lasso(script)?)</string>
	<key>foldingStartMarker</key>
	<string>(?x)(
		&lt;\?(?i:=|lasso(script)?)\b
		|(?i:if|inline|iterate|loop|match|protect|records|resultset|rows|while)(\(|:).*(;|$)
		|\/\*(?!.*\*\/)
	    |\{\s*$
	    |\{\^\s*$
		)</string>
	<key>foldingStopMarker</key>
	<string>(?x)(
		\s*\?&gt;
		|/(?i:if|inline|iterate|loop|match|protect|records|resultset|rows|while)(;|$)
		|^(?!.*?\/\*).*?\*\/
		|^\s*\}
		|^\s*\^\}
		)</string>
	<key>name</key>
	<string>Lasso</string>

	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>text.html.basic</string>

			<key>begin</key>
			<string>(?m)\A\s*(?=&lt;)</string>

			<key>end</key>
			<string>\a</string>

			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#lasso-html</string>
				</dict>
			</array>
		</dict>

		<dict>
			<key>name</key>
			<string>source.lasso</string>

			<key>begin</key>
			<string>\A</string>

			<key>end</key>
			<string>\a</string>

			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#lasso</string>
				</dict>
			</array>
		</dict>
	</array>


	<key>repository</key>
	<dict>
		<key>lasso</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.definition.type_trait.start.lasso</string>

					<key>begin</key>
					<string>(?i)\b(define)\s+(?=[_a-z][_0-9a-z]*\s*=&gt;\s*(type|trait|thread)\s*\{)</string>

					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.definition.lasso</string>
						</dict>
					</dict>

					<key>end</key>
					<string>(=&gt;)\s*(type|trait|thread)\s*\{</string>

					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.association.lasso</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.descriptors.lasso</string>
						</dict>
					</dict>

					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[_a-z][_0-9a-z]*</string>

							<key>name</key>
							<string>meta.name.type_trait.lasso</string>
						</dict>
					</array>
				</dict>

				<dict>
					<key>name</key>
					<string>meta.definition.method.start.lasso</string>

					<key>begin</key>
					<string>(?i)\b(define)\s+(?=[_a-z][_0-9a-z]*\s*=&gt;|\()</string>

					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.definition.lasso</string>
						</dict>
					</dict>

					<key>end</key>
					<string>\(|(=&gt;)</string>

					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.association.lasso</string>
						</dict>
					</dict>

					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[_a-z][_0-9a-z]*</string>

							<key>name</key>
							<string>meta.name.method.lasso</string>
						</dict>
					</array>
				</dict>

				<dict>
					<key>match</key>
					<string>(?i)\b(abort|case|define|else|if|inline|iterate|loop|loop_abort|loop_continue|loop_count|loop_key|loop_value|match|protect|records|resultset|return|rows|while)\b</string>
					<key>name</key>
					<string>keyword.control.lasso</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(library|include)(_once)?\b</string>
					<key>name</key>
					<string>keyword.control.import.lasso</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(public|private|protected|data|type|thread|trait|import|parent|provide|require)\b</string>
					<key>name</key>
					<string>keyword.descriptors.lasso</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(array|action_params?|boolean|bytes|capture|curl|currency|database_registry|date|dateandtime|decimal|delve|dir|duration|eacher|file|generateForEachKeyed|generateForEachUnKeyed|generateSeries|inline_type|integer|list|list_node|literal|local|locale|map|map_node
					|net_tcp|net_tcpssl|net_udp|net_udppacket|object|pair|pairup|paramdesc|pdf_barcode|pdf_chunk|pdf_color|pdf_doc|pdf_font|pdf_hyphenator|pdf_image|pdf_list|pdf_paragraph|pdf_phrase|pdf_read|pdf_table|pdf_text|pdf_typebase
					|percent|queriable_select|queriable_groupBy|queriable_grouping|queriable_groupJoin|queriable_join|queriable_orderBy|queriable_orderByDescending|queriable_selectMany|queriable_skip|queriable_take|queriable_thenBy|queriable_thenByDescending|queriable_where
					|queue|repeat|serialization_element|serialization_object_identity_compare|serialization_reader|serialization_writer|serialization_writer_ref|serialization_writer_standin|set|scientific
					|sqlite_column|sqlite_columnScanner|sqlite_currentrow|sqlite_db|sqlite_expressionGenerator|sqlite_query_stat|sqlite_results|sqlite_table|stack|staticarray|string|tie|timeonly|tree_base|tree_node|tree_nullNode|user_registry|var(iable)?|web_request|web_response|xml_element|xml_namednodemap_attr|xml_node|xml_nodelist|zip|zip_file)\b</string>
					<key>name</key>
					<string>storage.type.lasso</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>This is for the ljapi types</string>
					<key>match</key>
					<string>(?i)\b(jchar|jchararray|jbyte|jbytearray|jfloat|jint|jshort)\b</string>
					<key>name</key>
					<string>storage.type.lasso</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:void|null|true|false)\b</string>
					<key>name</key>
					<string>constant.language.lasso</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.lasso</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.lasso</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.lasso</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.lasso</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>`</string>
					<key>end</key>
					<string>`</string>
					<key>name</key>
					<string>string.quoted.backtick.lasso</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*\*(\!)?\s*$</string>
					<key>comment</key>
					<string>This now only highlights a docblock if the first line contains only /**
								- this is to stop highlighting everything as invalid when people do comment banners with /******** ...
								- Now matches /**! too - used for docblock templates</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.documentation.lasso</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.lasso</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(//).*?($\n?|(?=\?&gt;))</string>
					<key>name</key>
					<string>comment.line.double-slash.lasso</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\$[a-zA-Z_][a-zA-Z0-9_.]*</string>
					<key>name</key>
					<string>variable.other.thread.lasso</string>
				</dict>
				<dict>
					<key>match</key>
					<string>#[a-zA-Z_][a-zA-Z0-9_.]*</string>
					<key>name</key>
					<string>variable.other.local.lasso</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\s#1\s|\b(?i:self)\b)</string>
					<key>name</key>
					<string>variable.language.lasso</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\-\-|\+\+)</string>
					<key>name</key>
					<string>keyword.operator.increment-decrement.lasso</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\-|\+|\*|/|%)</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.lasso</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)(!|&amp;&amp;|\|\||\?|\bnot\b|\band\b|\bor\b)</string>
					<key>name</key>
					<string>keyword.operator.logical.lasso</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(=|:=|\+=|\-=|/=|%=)</string>
					<key>name</key>
					<string>keyword.operator.assignment.lasso</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(===|==|!==|!=|&lt;=|&gt;=|&lt;|&gt;|&gt;&gt;|!&gt;&gt;)</string>
					<key>name</key>
					<string>keyword.operator.comparison.lasso</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(-&gt;|&amp;)</string>
					<key>name</key>
					<string>keyword.operator.target.lasso</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(=&gt;)</string>
					<key>name</key>
					<string>keyword.operator.association.lasso</string>
				</dict>
			</array>
		</dict>

				<key>lasso-html</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;)([a-zA-Z0-9:]++)(?=[^&gt;]*&gt;&lt;/\2&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&gt;(&lt;)/)(\2)(&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.scope.between-tag-pair.html</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.html</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tag.any.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-stuff</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;\?)(xml)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.xml.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\?&gt;)</string>
					<key>name</key>
					<string>meta.tag.preprocessor.xml.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-generic-attribute</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string-double-quoted</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string-single-quoted</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;!--</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>--\s*&gt;</string>
					<key>name</key>
					<string>comment.block.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>--</string>
							<key>name</key>
							<string>invalid.illegal.bad-comments-or-CDATA.html</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;!</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>&gt;</string>
					<key>name</key>
					<string>meta.tag.sgml.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(DOCTYPE)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.doctype.html</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=&gt;)</string>
							<key>name</key>
							<string>meta.tag.sgml.doctype.html</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>"[^"&gt;]*"</string>
									<key>name</key>
									<string>string.quoted.double.doctype.identifiers-and-DTDs.html</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\[CDATA\[</string>
							<key>end</key>
							<string>]](?=&gt;)</string>
							<key>name</key>
							<string>constant.other.inline-data.html</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(\s*)(?!--|&gt;)\S(\s*)</string>
							<key>name</key>
							<string>invalid.illegal.bad-comments-or-CDATA.html</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:^\s+)?(&lt;)((?i:style))\b(?![^&gt;]*/&gt;)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.style.html</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&lt;/)((?i:style))(&gt;)(?:\s*\n)?</string>
					<key>name</key>
					<string>source.css.embedded.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-stuff</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(&gt;)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.html</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=&lt;/(?i:style))</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#embedded-code</string>
								</dict>
								<dict>
									<key>include</key>
									<string>source.css</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:^\s+)?(&lt;)((?i:script))\b(?![^&gt;]*/&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.script.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;=&lt;/(script|SCRIPT))(&gt;)(?:\s*\n)?</string>
					<key>endCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.js.embedded.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-stuff</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!&lt;/(?:script|SCRIPT))(&gt;)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.html</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.script.html</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(&lt;/)((?i:script))</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.comment.js</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(//).*?((?=&lt;/script)|$\n?)</string>
									<key>name</key>
									<string>comment.line.double-slash.js</string>
								</dict>
								<dict>
									<key>begin</key>
									<string>/\*</string>
									<key>captures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.comment.js</string>
										</dict>
									</dict>
									<key>end</key>
									<string>\*/|(?=&lt;/script)</string>
									<key>name</key>
									<string>comment.block.js</string>
								</dict>
								<dict>
									<key>include</key>
									<string>source.js</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;/?)((?i:body|head|html)\b)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.structure.any.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&gt;)</string>
					<key>name</key>
					<string>meta.tag.structure.any.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-stuff</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;/?)((?i:address|blockquote|dd|div|dl|dt|fieldset|form|frame|frameset|h1|h2|h3|h4|h5|h6|iframe|noframes|object|ol|p|ul|applet|center|dir|hr|menu|pre)\b)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.block.any.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tag.block.any.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-stuff</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;/?)((?i:a|abbr|acronym|area|b|base|basefont|bdo|big|br|button|caption|cite|code|col|colgroup|del|dfn|em|font|head|html|i|img|input|ins|isindex|kbd|label|legend|li|link|map|meta|noscript|optgroup|option|param|q|s|samp|script|select|small|span|strike|strong|style|sub|sup|table|tbody|td|textarea|tfoot|th|thead|title|tr|tt|u|var)\b)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.inline.any.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>((?: ?/)?&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tag.inline.any.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-stuff</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;/?)([a-zA-Z0-9:]+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.other.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tag.other.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-stuff</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;&gt;</string>
					<key>name</key>
					<string>invalid.illegal.incomplete.html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;</string>
					<key>name</key>
					<string>invalid.illegal.bad-angle-bracket.html</string>
				</dict>
			</array>
		</dict>






















		<key>embedded-code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#lasso_script</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lasso_brackets</string>
				</dict>
			</array>
		</dict>
		<key>entities</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.html</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.html</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&amp;)([a-zA-Z0-9]+|#[0-9]+|#x[0-9a-fA-F]+)(;)</string>
					<key>name</key>
					<string>constant.character.entity.html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&amp;</string>
					<key>name</key>
					<string>invalid.illegal.bad-ampersand.html</string>
				</dict>
			</array>
		</dict>
		<key>lasso_script</key>
		<dict>
			<key>begin</key>
			<string>(&lt;\?)(?i:=|lasso(script)?)</string>
			<key>end</key>
			<string>(\?&gt;)</string>
			<key>name</key>
			<string>source.lasso.embedded.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#lasso</string>
				</dict>
			</array>
		</dict>
		<key>lasso_brackets</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>source.lasso.embedded.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#lasso</string>
				</dict>
			</array>
		</dict>
		
		<key>smarty</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\{(literal)\})</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.smarty.embedded.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.built-in.smarty</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\{/(literal)\})</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>{{|{</string>
					<key>disabled</key>
					<integer>1</integer>
					<key>end</key>
					<string>}}|}</string>
					<key>name</key>
					<string>source.smarty.embedded.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.smarty</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>

		<key>string-double-quoted</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
		</dict>
		<key>string-single-quoted</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
		</dict>
		<key>tag-generic-attribute</key>
		<dict>
			<key>match</key>
			<string>\b([a-zA-Z\-:]+)</string>
			<key>name</key>
			<string>entity.other.attribute-name.html</string>
		</dict>
		<key>tag-id-attribute</key>
		<dict>
			<key>begin</key>
			<string>\b(id)\b\s*(=)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.id.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;='|")</string>
			<key>name</key>
			<string>meta.attribute-with-value.id.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.html</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.toc-list.id.html</string>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#embedded-code</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#entities</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.html</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.toc-list.id.html</string>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#embedded-code</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#entities</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>tag-stuff</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-id-attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-generic-attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
			</array>
		</dict>

	</dict>

	


	<key>scopeName</key>
	<string>file.lasso</string>
	<key>uuid</key>
	<string>ED5E138D-C4A8-4F7A-AAC6-74C315471D00</string>
</dict>
</plist>
